#Makefile.test

#TODO: You can use this like below. It's not a command !
#Rubbish :=$(shell perl deal.PL)

.PHONY : nop
nop: clean 
	@echo $(IM_TOP) "[makefile]"
	$(shell perl deal.PL)
	@echo "done."
clean:
	-@rm file.out -f
